export const SHOW_MAKE_ORDER_DIALOG = 'SHOW_MAKE_ORDER_DIALOG';
export const HIDE_MAKE_ORDER_DIALOG = 'HIDE_MAKE_ORDER_DIALOG';
export const NEW_PARCEL_ORDER = 'NEW_PARCEL_ORDER';
export const NEW_PARCEL_ORDER_SUCCESS_MESSAGE = 'NEW_PARCEL_ORDER_SUCCESS_MESSAGE';
export const NEW_PARCEL_ORDER_ERROR_MESSAGE = 'NEW_PARCEL_ORDER_ERROR_MESSAGE';



